#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header 
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on
sudo apt-get update -y
sudo apt-get install nginx -y
header="\t\tadd_header X-Served-By '$HOSTNAME';"
sudo sed -i "36i\ $header" /etc/nginx/sites-enabled/default
sudo service nginx restart
