#!/bin/bash
# A script that moves all files beginning with an uppercase letter to the directory /tmp/u.
# You can assume that the directory /tmp/u will exist when this script is run
mv [[:upper:]]* /tmp/u
