#!/usr/bin/env bash
# A Bash script that displays the username, user id, and home directory path of user of the file /etc/passwd
while read -r user uid home
do
    echo "$user $uid $home"
done </etc/passwd
