#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd, using the while loop + internal field seperator
while IFS=: read -r USERNAME PASSWORD U_ID GID INFO HOME SHELL
do
    echo "The user $USERNAME is part of the $GID gang, lives in $HOME and rides $SHELL. $U_ID's place is protected by the passcode $PASSWORD, more info about the user here: $INFO"
done </etc/passwd
