#!/usr/bin/env bash
# a Bash script that displays the content of
# the current directory in a list format
# where only the part of the name after the
# first dash is displayed
for i in *
do
    printf "%s\n" "$i" | cut -f2 -d"-"
done
