#!/usr/bin/env bash
# transfers a file from our client to a server
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Shell_Script" | sudo tee /usr/share/nginx/html/index.html
service nginx start
