#!/usr/bin/env bash
# custom 404 page
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Shell_Script" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
ns="location /redirect_me {\nrewrite ^(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n}"
sudo sed -i "30i $ns" /etc/nginx/sites-available/default
ns2="error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}"
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "35i $ns2" /etc/nginx/sites-available/default
sudo service nginx restart
